language: ruby
cache: bundler
script: bundle exec rspec

rvm:
  - 1.9.3
  - "2.0"
  - ruby-head
  - rbx-2
  - jruby
  - jruby-head

matrix:
  include:
    - rvm: "2.1"
      env: "RUN_COVERALLS=true"

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
