language: ruby
cache: bundler
script: bundle exec rspec

rvm:
  - 1.9.3
  - "2.0"
  - "2.1"
  - ruby-head
  - rbx-2
  - jruby
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
