language: ruby
cache: bundler
script: bundle exec rspec

gemfile:
  - gemfiles/Rails-4.2.gemfile
  - gemfiles/Rails-4.1.gemfile
  - gemfiles/Rails-4.0.gemfile

rvm:
  - 1.9.3
  - "2.1"
  - "2.0"
  - rbx-2
  - jruby

matrix:
  exclude:
    - rvm: "2.1"
      gemfile: gemfiles/Rails-4.1.gemfile

  include:
    - rvm: "2.1"
      gemfile: gemfiles/Rails-4.1.gemfile
      env: RUN_COVERALLS=true

    - rvm: "ruby-head"
      gemfile: gemfiles/Rails-4.1.gemfile

    - rvm: "jruby-head"
      gemfile: gemfiles/Rails-4.1.gemfile

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - gemfile: gemfiles/Rails-4.2.gemfile
