language: ruby
cache: bundler
script: bundle exec rspec

gemfile:
  - gemfiles/Rails-4.2.gemfile
  - gemfiles/Rails-4.1.gemfile
  - gemfiles/Rails-4.0.gemfile
  - gemfiles/Rails-3.2.gemfile
  - gemfiles/Rails-3.1.gemfile
  - gemfiles/Rails-3.0.gemfile

rvm:
  - 1.9.3

matrix:
  include:
    # Testing gem against all popular Rubies is of course important, but
    # do not repeat it for every ActiveRecord version.  Do not hunt
    # for ActiveRecord compatibility issues with various Rubies.
    - rvm: "2.0"
      gemfile: gemfiles/Rails-4.2.gemfile
    - rvm: "2.1"
      gemfile: gemfiles/Rails-4.2.gemfile
    - rvm: "2.2"
      gemfile: gemfiles/Rails-4.2.gemfile
    - rvm: rbx-2
      gemfile: gemfiles/Rails-4.2.gemfile
    - rvm: rbx-3
      gemfile: gemfiles/Rails-4.2.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/Rails-4.2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/Rails-4.2.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/Rails-4.2.gemfile

    # One build designated to check test coverage with Coveralls.
    - rvm: "2.3.0"
      gemfile: gemfiles/Rails-4.2.gemfile
      env: RUN_COVERALLS=true

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - gemfile: gemfiles/Rails-head.gemfile
